/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryCreate
 */
export interface CategoryCreate {
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryCreate
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the CategoryCreate interface.
 */
export function instanceOfCategoryCreate(value: object): value is CategoryCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CategoryCreateFromJSON(json: any): CategoryCreate {
    return CategoryCreateFromJSONTyped(json, false);
}

export function CategoryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function CategoryCreateToJSON(json: any): CategoryCreate {
    return CategoryCreateToJSONTyped(json, false);
}

export function CategoryCreateToJSONTyped(value?: CategoryCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'is_active': value['isActive'],
    };
}

