/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryUpdate
 */
export interface CategoryUpdate {
    /**
     * 
     * @type {string}
     * @memberof CategoryUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryUpdate
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the CategoryUpdate interface.
 */
export function instanceOfCategoryUpdate(value: object): value is CategoryUpdate {
    return true;
}

export function CategoryUpdateFromJSON(json: any): CategoryUpdate {
    return CategoryUpdateFromJSONTyped(json, false);
}

export function CategoryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function CategoryUpdateToJSON(json: any): CategoryUpdate {
    return CategoryUpdateToJSONTyped(json, false);
}

export function CategoryUpdateToJSONTyped(value?: CategoryUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'is_active': value['isActive'],
    };
}

