/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrollmentCreate
 */
export interface EnrollmentCreate {
    /**
     * 
     * @type {number}
     * @memberof EnrollmentCreate
     */
    studentId: number;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentCreate
     */
    courseId: number;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentCreate
     */
    assignerId: number;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentCreate
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentCreate
     */
    enrolledAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentCreate
     */
    deadline?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentCreate
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the EnrollmentCreate interface.
 */
export function instanceOfEnrollmentCreate(value: object): value is EnrollmentCreate {
    if (!('studentId' in value) || value['studentId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('assignerId' in value) || value['assignerId'] === undefined) return false;
    return true;
}

export function EnrollmentCreateFromJSON(json: any): EnrollmentCreate {
    return EnrollmentCreateFromJSONTyped(json, false);
}

export function EnrollmentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'studentId': json['student_id'],
        'courseId': json['course_id'],
        'assignerId': json['assigner_id'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'enrolledAt': json['enrolled_at'] == null ? undefined : (new Date(json['enrolled_at'])),
        'deadline': json['deadline'] == null ? undefined : (new Date(json['deadline'])),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function EnrollmentCreateToJSON(json: any): EnrollmentCreate {
    return EnrollmentCreateToJSONTyped(json, false);
}

export function EnrollmentCreateToJSONTyped(value?: EnrollmentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'student_id': value['studentId'],
        'course_id': value['courseId'],
        'assigner_id': value['assignerId'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'enrolled_at': value['enrolledAt'] == null ? undefined : ((value['enrolledAt']).toISOString().substring(0,10)),
        'deadline': value['deadline'] == null ? undefined : ((value['deadline'] as any).toISOString().substring(0,10)),
        'is_active': value['isActive'],
    };
}

