/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleCreate
 */
export interface RoleCreate {
    /**
     * 
     * @type {string}
     * @memberof RoleCreate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the RoleCreate interface.
 */
export function instanceOfRoleCreate(value: object): value is RoleCreate {
    return true;
}

export function RoleCreateFromJSON(json: any): RoleCreate {
    return RoleCreateFromJSONTyped(json, false);
}

export function RoleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function RoleCreateToJSON(json: any): RoleCreate {
    return RoleCreateToJSONTyped(json, false);
}

export function RoleCreateToJSONTyped(value?: RoleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

