/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrollmentResponse } from './EnrollmentResponse';
import {
    EnrollmentResponseFromJSON,
    EnrollmentResponseFromJSONTyped,
    EnrollmentResponseToJSON,
    EnrollmentResponseToJSONTyped,
} from './EnrollmentResponse';
import type { RoleResponse } from './RoleResponse';
import {
    RoleResponseFromJSON,
    RoleResponseFromJSONTyped,
    RoleResponseToJSON,
    RoleResponseToJSONTyped,
} from './RoleResponse';
import type { TaskCompletionResponse } from './TaskCompletionResponse';
import {
    TaskCompletionResponseFromJSON,
    TaskCompletionResponseFromJSONTyped,
    TaskCompletionResponseToJSON,
    TaskCompletionResponseToJSONTyped,
} from './TaskCompletionResponse';
import type { CourseResponse } from './CourseResponse';
import {
    CourseResponseFromJSON,
    CourseResponseFromJSONTyped,
    CourseResponseToJSON,
    CourseResponseToJSONTyped,
} from './CourseResponse';

/**
 * 
 * @export
 * @interface UserResponseTasksAndCourses
 */
export interface UserResponseTasksAndCourses {
    /**
     * 
     * @type {string}
     * @memberof UserResponseTasksAndCourses
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseTasksAndCourses
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseTasksAndCourses
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseTasksAndCourses
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponseTasksAndCourses
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserResponseTasksAndCourses
     */
    userId: number;
    /**
     * 
     * @type {RoleResponse}
     * @memberof UserResponseTasksAndCourses
     */
    role: RoleResponse;
    /**
     * 
     * @type {Array<CourseResponse>}
     * @memberof UserResponseTasksAndCourses
     */
    createdCourses?: Array<CourseResponse>;
    /**
     * 
     * @type {Array<EnrollmentResponse>}
     * @memberof UserResponseTasksAndCourses
     */
    enrolledCourses?: Array<EnrollmentResponse>;
    /**
     * 
     * @type {Array<EnrollmentResponse>}
     * @memberof UserResponseTasksAndCourses
     */
    assignedCourses?: Array<EnrollmentResponse>;
    /**
     * 
     * @type {Array<TaskCompletionResponse>}
     * @memberof UserResponseTasksAndCourses
     */
    taskCompletions?: Array<TaskCompletionResponse>;
}

/**
 * Check if a given object implements the UserResponseTasksAndCourses interface.
 */
export function instanceOfUserResponseTasksAndCourses(value: object): value is UserResponseTasksAndCourses {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserResponseTasksAndCoursesFromJSON(json: any): UserResponseTasksAndCourses {
    return UserResponseTasksAndCoursesFromJSONTyped(json, false);
}

export function UserResponseTasksAndCoursesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseTasksAndCourses {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'userId': json['user_id'],
        'role': RoleResponseFromJSON(json['role']),
        'createdCourses': json['created_courses'] == null ? undefined : ((json['created_courses'] as Array<any>).map(CourseResponseFromJSON)),
        'enrolledCourses': json['enrolled_courses'] == null ? undefined : ((json['enrolled_courses'] as Array<any>).map(EnrollmentResponseFromJSON)),
        'assignedCourses': json['assigned_courses'] == null ? undefined : ((json['assigned_courses'] as Array<any>).map(EnrollmentResponseFromJSON)),
        'taskCompletions': json['task_completions'] == null ? undefined : ((json['task_completions'] as Array<any>).map(TaskCompletionResponseFromJSON)),
    };
}

export function UserResponseTasksAndCoursesToJSON(json: any): UserResponseTasksAndCourses {
    return UserResponseTasksAndCoursesToJSONTyped(json, false);
}

export function UserResponseTasksAndCoursesToJSONTyped(value?: UserResponseTasksAndCourses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'is_active': value['isActive'],
        'user_id': value['userId'],
        'role': RoleResponseToJSON(value['role']),
        'created_courses': value['createdCourses'] == null ? undefined : ((value['createdCourses'] as Array<any>).map(CourseResponseToJSON)),
        'enrolled_courses': value['enrolledCourses'] == null ? undefined : ((value['enrolledCourses'] as Array<any>).map(EnrollmentResponseToJSON)),
        'assigned_courses': value['assignedCourses'] == null ? undefined : ((value['assignedCourses'] as Array<any>).map(EnrollmentResponseToJSON)),
        'task_completions': value['taskCompletions'] == null ? undefined : ((value['taskCompletions'] as Array<any>).map(TaskCompletionResponseToJSON)),
    };
}

