services:
  api:
    build: ../api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../api:/code
    env_file:
      - ../api/.env
    restart: always

  frontend:
    container_name: frontend-dev
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api
